[package]
name = "booter"
version = "0.1.0"
edition = "2021"

[dependencies]
kapi = { workspace = true, features = ["userspace"] }
sync = { workspace = true }
serial = { workspace = true }
log = "0.4.21"
