[package]
name = "smoke"
version = "0.1.0"
edition = "2021"

[dependencies]
kapi = { workspace = true, features = ["userspace"] }
sync = { workspace = true }
stack_list = { workspace = true }
serial = { workspace = true }

uart_16550 = "0.3.0"
log = "0.4.22"
