[package]
name = "memory_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serial = { workspace = true }
kapi = { workspace = true, features = ["userspace"] }
entry = { workspace = true }
log = "0.4.21"
