.TH LIMINE-VERSION 1 "version 4.20230530.0" "May 2023"

.SH NAME
limine-version \- print Limine version

.SH SYNOPSIS
.B limine-version

.SH DESCRIPTION
\fBlimine-version\fR prints the version number of the installed copy of Limine
to standard output.

.SH BUGS
Please report bugs via
.IR https://github.com/limine-bootloader/limine/issues .

.SH HOMEPAGE
.I https://limine-bootloader.org/

.SH SEE ALSO
.BR limine-deploy (1)
.BR limine-enroll-config (1)
